# Dependencies
markdown:         red carpet  #kramdown #
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Computación Visual
tagline:          'Universidad Nacional de Colombia'
description:      'Un grupo de Computación Visual de la Universidad Nacional de Colombia'

     

paginate:         5

# Custom vars
version:          2.0.0

